# Generated by Django 6.1.1 on 2026-09-08 17:04

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='member_name_unique_ci', violation_error_message='A member with that name already exists.')],
            },
        ),
    ]
