# Generated by Django 6.1.1 on 2026-09-08 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5, agreed by the club when the book is finished.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('finished_on'), descending=True, nulls_last=True), models.OrderBy(models.F('started_on'), descending=True, nulls_last=True), '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_book', violation_error_message="Another book is already the club's current read."), models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='book_rating_1_to_5', violation_error_message='A rating runs from 1 to 5.')],
            },
        ),
    ]
