# Generated by Django 6.1.1 on 2026-09-08 18:52

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='club.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='club.member')),
            ],
            options={
                'verbose_name_plural': 'progress',
                'ordering': ['-pages_read', django.db.models.functions.text.Lower('member__name')],
                'constraints': [models.UniqueConstraint(fields=('book', 'member'), name='one_progress_row_per_member_per_book', violation_error_message='That member already has progress recorded on this book.')],
            },
        ),
    ]
