# Generated by Django 6.1.1 on 2026-09-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='club.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='club.question')),
            ],
            options={
                'ordering': ['created_on', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('question', 'member'), name='one_answer_per_member_per_question', violation_error_message='You have already answered this one — edit that answer instead.')],
            },
        ),
    ]
