# Generated by Django 6.1.1 on 2026-09-08 20:15

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='club.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='club.member')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('member__name')],
                'constraints': [models.UniqueConstraint(fields=('book', 'member'), name='one_rating_per_member_per_book', violation_error_message='You have already rated this one — change that score instead.'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='member_rating_1_to_5', violation_error_message='A rating runs from 1 to 5.')],
            },
        ),
    ]
