# Generated by Django 6.1.1 on 2026-09-10 20:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_memberrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': [models.OrderBy(models.Case(models.When(book__total_chapters__gt=0, then=models.F('chapters_read')), default=models.F('pages_read')), descending=True, nulls_last=True), django.db.models.functions.text.Lower('member__name')], 'verbose_name_plural': 'progress'},
        ),
        migrations.AddField(
            model_name='book',
            name='total_chapters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='chapters_read',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('total_pages__isnull', True), ('total_chapters__isnull', True), _connector='OR'), name='book_has_one_denominator', violation_error_message='A book is measured in pages or in chapters, not both.'),
        ),
    ]
